permalink: /:categories/:year/:month/:day/:title 

plugins:
  - jekyll-redirect-from

exclude:
  - .rvmrc
  - .rbenv-version
  - README.md
  - Rakefile
  - changelog.md
  - vendor

highlighter: rouge
markdown: kramdown
kramdown:
   input: GFM

defaults:
  - scope: {path: ""}
    values: {layout: "default"}
  - scope: {path: "documentation"}
    values: {layout: "documentation"}
  - scope: {path: "gallery/full"}
    values: {gallery_full: true}

title: ilastik
author:
  name: the ilastik developers
  email: team@ilastik.org
  github: ilastik
