permalink: /:categories/:year/:month/:day/:title 

plugins:
  - jekyll-redirect-from

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter : rouge
markdown: kramdown
kramdown:
   input: GFM

title : ilastik
author :
  name : the ilastik developers 
  email : team@ilastik.org
  github : ilastik

production_url : http://ilastik.org
baseurl: http://ilastik.org
relative_permalinks: false
